#
# Check https://docs.gitlab.com/ee/ci/yaml/README.html for more details
# Use https://gitlab.com/dealdotcom/chat-firebase-js/-/ci/lint to test this file
#
image: node:12.3.1

stages:
  - setup
  - execute
  - deploy

# https://docs.gitlab.com/ee/ci/yaml/#anchors
.cache_rw: &cache_rw
  paths: &cache_paths
    - node_modules/

.cache_ro: &cache_readonly
  <<: *cache_rw
  policy: pull

.npm_install:
  before_script: &npm_install
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN_RO}" > .npmrc
    - npm i

prepare:
  stage: setup
  cache: *cache_rw
  script: *npm_install
  # Only running this on master to refresh NPM cache
  # branches will reuse this cache and refresh locally
  only:
    - master

# test:
#   stage: execute
#   extends: .npm_install
#   cache: *cache_readonly
#   script:
#     - npm run test
#   only:
#     - branches

build:
  stage: execute
  extends: .npm_install
  cache: *cache_readonly
  script:
    - npm run rebuild
  only:
    - branches

publish:
  stage: deploy
  environment: production
  extends: .npm_install
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm semantic-release
  only:
    - master
